#!/bin/bash
clear
# Mendefinisikan warna untuk pesan
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
export LIGHT='\033[0;37m'
export PINK='\033[0;35m'
export ORANGE='\033[38;5;208m'
export PINK_BG='\033[45;1;97m'
export BIRU='\033[44;1;97m'
export RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
export NC='\033[0m'
export INDIGO='\033[38;5;54m'
export TEAL='\033[38;5;30m'
export WHITE='\033[1;37m'
clear
# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

export TIME="10"
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear

# . Liner 
function baris_panjang() {
echo -e " ${TEAL}————————————————————————————————————————${NC}"
}

function xdxl_Banner() {
clear
baris_panjang
echo -e "  ${PURPLE}        SKARTI TUNNELING ${NC}"
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "\033[2;35m      Terimakasih sudah menggunakan \033[0m"
echo -e "\033[2;35m         Script Credit by skarti \033[0m"
baris_panjang
exit 1
}

# // jalankan perintah sleep 3 & loading $!
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}

xdxl_Banner
  echo -e ""
  echo -e " ${WHITE}Just input a number for${NC} ${GREEN}Limit IP${NC}"
  echo -e ""
  echo -e " ${YELLOW}0${NC} for No Limit"
  echo -e ""
baris_panjang
echo ""
read -p " Username      : " Login
read -p " Password      : " Pass
read -p " Limit (IP)    : " iplimit
read -p " Expired (day) : " masaaktif
echo
clear

#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip/
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"| passwd $Login &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
  echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
else
echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
fi
clear

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>SSH OVPN Account     </code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Username         : </code> <code>$Login</code>
<code>Password         : </code> <code>$Pass</code>
<code>Limit Quota      : </code> <code>$Quota</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>IP               : $IP</code>
<code>Host             : </code> <code>$domain</code>
<code>Port OpenSSH     : 443, 80, 22</code>
<code>Port Dropbear    : 443, 109</code>
<code>Port SSH WS      : 80, 8080, 8081-9999 </code>
<code>Port SSH UDP     : 1-65535 </code>
<code>Port SSH SSL WS  : 443</code>
<code>Port SSL/TLS     : 400-900</code>
<code>Port OVPN WS SSL : 443</code>
<code>Port OVPN SSL    : 443</code>
<code>Port OVPN TCP    : 443, 1194</code>
<code>Port OVPN UDP    : 2200</code>
<code>BadVPN UDP       : 7100, 7300, 7300</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>SSH WEBSOCKET    : </code><code>$domain:80@$Login:$Pass</code>
<code>SSH SSL          : </code><code>$domain:443@$Login:$Pass</code>
<code>SSH UDP          : </code><code>$domain:1-65535@$Login:$Pass</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Payload WSS      : </code><code>GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Ping: clients3.google.com[crlf]Sec-WebSocket-Extensions: superspeed[crlf][crlf]</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
OVPN Download : https://$domain:81/
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Save Link Account: </code>https://$domain:81/ssh-$Login.txt
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Active During         : $masaaktif Hari
Made On          : $tnggl
Expire At        : $expe
<code>◇━━━━━━━━━━━━━━━━━◇</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="<code>◇━━━━━━━━━━━━━━━━━◇
*_PEMBELIAN BERHASIL_*
◇━━━━━━━━━━━━━━━━━◇
-» PRODUCT : SSH
-» REGION : $CITY
-» REQ CONFIG : 
-» REQ NAME : $Login
-» DEVICE : $iplimit IP
-» PRICE : 
-» ACTIVE : $masaaktif HARI
-» TGL EXP : $expe
◇━━━━━━━━━━━━━━━━━◇
$nama </code>"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Ping: clients3.google.com[crlf]Sec-WebSocket-Extensions: superspeed[crlf][crlf]"

PAYLOADTLS="GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADHANCED="HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf]"

# Details ACcount
function Details_Ssh(){
xdxl_Banner
echo -e " ${PURPLE}           SSH/Dropbear${NC}"
baris_panjang
echo -e "\033[3;37m Host         : $domain \033[0m"
echo -e "\033[3;37m Username     : $Login \033[0m"
echo -e "\033[3;37m Password     : $Pass \033[0m"
echo -e "\033[3;37m Limit IP     : ${iplimit} Device \033[0m"
baris_panjang
echo -e "\033[3;37m OpenSSH      : 22, 80 \033[0m"
echo -e "\033[3;37m Dropbear     : 80, 143 \033[0m"
echo -e "\033[3;37m OpenSSH SSL  : 443 \033[0m"
echo -e "\033[3;37m Dropbear SSL : 443 \033[0m"
baris_panjang
echo -e "\033[3;37m SSH WS NTLS  : 80,8080,8880,2082 \033[0m"
echo -e "\033[3;37m SSH WS TLS   : 443 \033[0m"
baris_panjang
echo -e "\033[3;37m SSH UDP      : 1-65535 \033[0m"
echo -e "\033[3;37m OpenVPN UDP  : 2200 \033[0m"
baris_panjang
}



function Copy_Faste(){
echo -e " ${PURPLE}             OpenVPN${NC}"
baris_panjang
echo -e "\033[3;37m https://$domain:81/ "
}



function Details_Payload(){
baris_panjang
echo -e " ${PURPLE}            Payload WS${NC}"
baris_panjang
echo -e "\033[3;37m ${PAYLOADWS}\033[0m"
baris_panjang
}



function Expiry_Details(){
echo -e "\033[33m       Expired  : $expe \033[0m"
}


xdxl_Banner
Details_Ssh
Copy_Faste
Details_Payload
Expiry_Details
Sc_Credit
