#!/bin/bash

# Pendefinisian warna
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\e[0m'

# Fungsi untuk status layanan bot
bot_service=$(systemctl status sktvpn | grep active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
if [[ $bot_service == "running" ]]; then 
   sts_bot="${GREEN}[ON]${NC}"
else
   sts_bot="${RED}[OFF]${NC}"
fi

# Fungsi untuk menampilkan header
function xdxl_Banner() {
    clear
    echo -e "${YELLOW} ——————————————————————————————————— ${NC}"
    echo -e "${GREEN}           BOT MANAGEMENT            ${NC}"
    echo -e "${YELLOW} ——————————————————————————————————— ${NC}"
}

# Menu utama
while true; do
    xdxl_Banner
    echo -e " Status Bot: ${sts_bot}"
    echo -e " 1. Create Bot"
    echo -e " 2. Delete Bot"
    echo -e " 3. Stop Bot"
    echo -e " 4. Restart Bot"
    echo -e " 5. Auto Backup Bot"
    echo -e " x. EXIT"
    echo -e "${YELLOW} ----------------------------------- ${NC}"
    read -p " Pilih menu: " opt
    case $opt in
         1) clear ; wget https://raw.githubusercontent.com/raffasyaa/duar/main/coid/sktvpn.sh && chmod +x sktvpn.sh && ./sktvpn.sh ;;
         2) clear ; hapus-bot ;;
         3) clear ; stop-bot ;;
         4) clear ; restart-bot ;;
         5) clear ; autobackup ;;
         x) clear; echo "Keluar..."; exit ;;
        *) echo -e "${RED}Opsi tidak valid!${NC}"; sleep 1 ;;
    esac
done
