#!/bin/bash
clear

# Mendefinisikan warna untuk pesan
export FONT="\033[0m"
export REDBLD="\033[0m\033[91;1m"
export Green="\e[92;1m"
export RED='\033[0;31m'
export GREENBG="\033[42;37m"
export REDBG="\033[41;37m"
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
export LIGHT='\033[0;37m'
export PINK='\033[0;35m'
export ORANGE='\033[38;5;208m'
export PINK_BG='\033[45;1;97m'
export RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
export NC='\033[0m'
export BIRU='\033[44;1;97m'
export INDIGO='\033[38;5;54m'
export TEAL='\033[38;5;30m'
export WHITE='\033[1;37m'


# // GETTINGS SYSTEM
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
clear

# Mengambil informasi sistem
OS=$(lsb_release -ds)
TRAM=$( free -m | awk 'NR==2 {print $2}' )
URAM=$( free -m | awk 'NR==2 {print $3}' )
UPTIME=$(uptime -s)
current_time=$(date "+%Y-%m-%d %H:%M:%S")
total_uptime=$(date -ud@$(( $(date -d "$current_time" +%s) - $(date -d "$UPTIME" +%s) )) +'%j days, %H hours')

# Hilangkan nol di depan pada days dan hours
formatted_uptime=$(uptime -p | cut -d " " -f 2-10)
IP_VPS=$(curl -s ipinfo.io/ip )
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
DOMAIN=$(cat /etc/xray/domain)

# Mengambil informasi IP lengkap dari ipinfo.io
IP_INFO=$(curl -s "http://ipinfo.io/$IP_VPS/json")
IP_REGION=$(echo "$IP_INFO" | jq -r '.region')
IP_COUNTRY=$(echo "$IP_INFO" | jq -r '.country')
IP_LOC=$(echo "$IP_INFO" | jq -r '.loc')

# Fungsi untuk mengambil total bandwidth menggunakan vnstat
vnstat_output=$(vnstat -y 1 --style 0 | sed -n 6p)
download=$(echo $vnstat_output | awk '{printf "%s %s", $2, $3}')
upload=$(echo $vnstat_output | awk '{printf "%s %s", $5, $6}')
total_usage=$(echo $vnstat_output | awk '{printf "%s %s", $8, $9}')

# Menggabungkan download dan upload menjadi satu baris
total_usage_line=$(printf "${TEAL}❖ ${WHITE}Total Usage    :${ORANGE} %s" "$total_usage ${CYAN}")
total_upload=$(printf "${TEAL}❖ ${WHITE}Total Upload   :${ORANGE} %s" "$upload ${CYAN}")
total_download=$(printf "${TEAL}❖ ${WHITE}Total Download :${ORANGE} %s" "$download ${CYAN}")

 
# RUNNING HAPROXY
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="\033[92;1mON${NC}"
else
   status_haproxy="\033[91;1m⛔${NC} "
fi
 
# RUNNING XRAY
if [[ $xray_service == "running" ]]; then 
   status_xray="\033[92;1mON${NC}"
else
   status_xray="\033[91;1m⛔${NC} "
fi
 
# RUNNING NGINX
if [[ $nginx_service == "running" ]]; then 
   status_nginx="\033[92;1mON${NC}"
else
   status_nginx="\033[91;1m⛔${NC} "
fi

# RUNNING DROPBEAR
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="\033[92;1mGOOD${NC}"
else
   status_dropbear="\033[91;1mCRAZY${NC} "
fi

    clear
    echo -e " ${TEAL}╭════════════════════════════════════════════════╮${NC}"
    echo -e " ${TEAL}│ ${NC}${RED_BG}               ❖ SKT AIO PROJECT  ❖           ${NC}${TEAL} │${NC}"
    echo -e " ${TEAL}╰════════════════════════════════════════════════╯${NC}"
    echo -e " ${TEAL}╭────────────────────────────────────────────────╮${NC}"
    echo -e " ${TEAL}│${NC} ${WHITE}OS${NC}        : $OS"
    echo -e " ${TEAL}│${NC} ${WHITE}RAM${NC}       : ${URAM} Mb / ${TRAM} Mb"
    echo -e " ${TEAL}│${NC} ${WHITE}CITY${NC}      : $IP_REGION"
    echo -e " ${TEAL}│${NC} ${WHITE}ISP${NC}       : $ISP"
    echo -e " ${TEAL}│${NC} ${WHITE}IP VPS${NC}    : ${TEAL}$IP_VPS${NC}"
    echo -e " ${TEAL}│${NC} ${WHITE}DOMAIN${NC}    : ${TEAL}$DOMAIN${NC}"
    echo -e " ${TEAL}│${NC} ${WHITE}UPTIME${NC}    : $formatted_uptime"
    echo -e " ${TEAL}╰────────────────────────────────────────────────╯${NC}"
    echo -e " ${TEAL}╭════════════════════════════════════════════════╮${NC}"
    echo -e " ${TEAL}│${NC}${ORANGE}  NGINX : $status_nginx${NC} ${TEAL}│${NC} ${ORANGE} XRAY :${NC} $status_xray ${TEAL}│${NC} ${ORANGE} PROXY :${NC} $status_haproxy ${NC}${TEAL}│${NC} $status_dropbear ${TEAL} │ ${NC} "
    echo -e " ${TEAL}╰════════════════════════════════════════════════╯${NC}"
    echo -e " ${TEAL}╭════════════════════════════════════════════════╮${NC}"
    echo -e " ${TEAL}│${NC} ${ORANGE}$total_usage_line${NC}"
    echo -e " ${TEAL}│${NC} ${ORANGE}$total_upload${NC}"
    echo -e " ${TEAL}│${NC} ${ORANGE}$total_download${NC}"
    echo -e " ${TEAL}╰────────────────────────────────────────────────╯${NC}"
    echo -e " ${TEAL}╭════════════════════════════════════════════════╮${NC}"
    echo -e " ${TEAL}│${NC}${BIRU}                ❖ MENU SERVICE ❖                ${NC}${TEAL}│${NC}"
    echo -e " ${TEAL}╰════════════════════════════════════════════════╯${NC}"
    echo -e " ${TEAL}╭────────────────────────────────────────────────╮${NC}"
    echo -e " ${TEAL}│\033[0m${NC} [${TEAL}01${NC}] ${WHITE}✦${NC} ${NC}CREATE SSH     ${NC}${TEAL}│${NC} [${TEAL}08${NC}] ${WHITE}✦${NC} ${NC}FEATURES       ${NC}${TEAL} │${NC}"
    echo -e " ${TEAL}│\033[0m${NC} [${TEAL}02${NC}] ${WHITE}✦${NC} ${NC}CREATE XRAY    ${NC}${TEAL}│${NC} [${TEAL}09${NC}] ${WHITE}✦${NC} ${NC}BENCHMARK      ${NC}${TEAL} │${NC}"
    echo -e " ${TEAL}│\033[0m${NC} [${TEAL}03${NC}] ${WHITE}✦${NC} ${NC}CREATE TROJAN  ${NC}${TEAL}│${NC} [${TEAL}10${NC}] ${WHITE}✦${NC} ${NC}SET WARP       ${NC}${TEAL} │${NC}"
    echo -e " ${TEAL}│\033[0m${NC} [${TEAL}04${NC}] ${WHITE}✦${NC} ${NC}CREATE SLOWDNS ${NC}${TEAL}│${NC} [${TEAL}11${NC}] ${WHITE}✦${NC} ${NC}REBUILD VPS    ${NC}${TEAL} │${NC}"
    echo -e " ${TEAL}│\033[0m${NC} [${TEAL}05${NC}] ${WHITE}✦${NC} ${NC}SET BACKUP     ${NC}${TEAL}│${NC} [${TEAL}12${NC}] ${WHITE}✦${NC} ${NC}MONITOR CPU    ${NC}${TEAL} │${NC}"
    echo -e " ${TEAL}│\033[0m${NC} [${TEAL}06${NC}] ${WHITE}✦${NC} ${NC}SET BOT API    ${NC}${TEAL}│${NC} [${TEAL}13${NC}] ${WHITE}✦${NC} ${NC}UPDATE SCRIPT  ${NC}${TEAL} │${NC}"
    echo -e " ${TEAL}│\033[0m${NC} [${TEAL}07${NC}] ${WHITE}✦${NC} ${NC}SET BOT NOTIF  ${NC}${TEAL}│${NC} [${TEAL}xx${NC}] ${WHITE}✦${NC} ${NC}EXIT           ${NC}${TEAL} │${NC}"
    echo -e " ${TEAL}╰────────────────────────────────────────────────╯${NC}"

read -p " ➣ Your Choice :  " semvak
case $semvak in
1) clear ; skt-menu-ssh ;;   # menu ssh
2) clear ; m-xray ;;  # menu vmess/vless
3) clear ; m-tro ;;   # menu trojan
4) clear ; skt-menu-slowdns ;;      # menu slowdns
5) clear ; semvak-backup-menu ;;   # menu backup & restore
6) clear ; skt-bot ;;   # menu bot reseller
7) clear ; skt-bot-notif ;; #menu bot notif
8) clear ; skarti-feature ;;   # menu managers
9) clear ; wget -q https://raw.githubusercontent.com/raffasyaa/cekpepes/main/benchmarkmenu && bash benchmarkmenu ;; #Cek SPek VPS
10) clear ; wget -q https://raw.githubusercontent.com/raffasyaa/W4rp/main/warpmenu && bash warpmenu ;;   # Menu Warp
11) clear ; wget -q https://raw.githubusercontent.com/raffasyaa/rebuildpepes/main/rebuildpepesmenu && bash rebuildpepesmenu ;; #Rebuild Pepes
12) clear ; gotop ;; # menu monitoring cpu
13) clear ; skarti-update ;; #Update script
xx) exit ;;

esac