#!/bin/bash
clear

# Mendefinisikan warna untuk pesan
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
export LIGHT='\033[0;37m'
export PINK='\033[0;35m'
export ORANGE='\033[38;5;208m'
export PINK_BG='\033[45;1;97m'
export BIRU='\033[44;1;97m'
export RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
export NC='\033[0m'
export INDIGO='\033[38;5;54m'
export TEAL='\033[38;5;30m'
export WHITE='\033[1;37m'


  echo -e "${CYAN} ——————————————————————————— ${NC} "
  echo -e " ${BIRU}         BACKUP MENU      ${NC} "
  echo -e "${CYAN} ——————————————————————————— ${NC} "
  echo -e "${WHITE} 1. Backup Vps Data ${NC}"
  echo -e "${WHITE} 2. Restore Vps Data ${NC}"
  echo -e "${WHITE} 3. Auto Backup Vps ${NC}"
  echo -e ""
  echo -e "${RED} x. Back to menu ${NC}"
  echo -e "${CYAN} ——————————————————————————— ${NC} "
  echo -e ""
read -p " Your Choice :  " sktbackup
case $sktbackup in
1) clear ; semvak-backup ;;
2) clear ; semvak-restore ;;
3) clear ; semvak-autobackup ;;
x) menu ;;
esac
