#!/bin/bash
y='\033[1;93m'
c="\033[0;36m"
g="\e[92;1m"
r="\033[1;31m"
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
yell='\e[33m'
BGX="\033[42m"
END='\e[0m'
bc="\e[5;36m"
ungu='\033[0;35m'
Green_background="\033[42;37m"
Red_background="\033[41;37m"
Suffix="\033[0m"
NC='\e[0m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
White="\033[97;1m"
Green="\033[92;1m"
Cyan="\033[96;1m"
Xark='\e[0m'
BG_BLU="\033[44;1m" # BG BIRU
nama=$(cat /etc/xray/username)
clear
function xdxl_Banner() {
clear
baris_panjang
echo -e "\033[95;1m     $nama       \033[0m"
baris_panjang
}

function baris_panjang() {
  echo -e "${BlueCyan} ———————————————————————————————————————${Xark}"
}
function ATAS() {
  echo -e     "${ungu}                FEATURES               ${Xark} "
}

function  FIXX() {
  echo -e  " ${BG_BLU}               MENU FIXX              ${Xark}"
}

function  CLEAR() {
  echo -e  " ${BG_BLU}               MENU CLEAR             ${Xark}"
}


function  INFORMATION() {
  echo -e  " ${BG_BLU}              INFORMATION             ${Xark}"
}


function Create_Bot_Notif() {
  create-bot-notif
}


function Info_Port() {
  semvak-cek-port
}

# Banner 
function Banner(){
clear
baris_panjang
ATAS
baris_panjang
}


function Menu_Lambofgod() {
baris_panjang
echo -e "  1.) Check Service "  
echo -e "  2.) Restart Service   " 
echo -e "  3.) Auto Reboot	  " 
echo -e "  4.) Install SlowDns    " 
baris_panjang
FIXX
baris_panjang
echo -e "  5.) Change Banner      "  
echo -e "  6.) Change Domain      "  
echo -e "  7.) Fix Haproxy       "  
echo -e "  8.) Fix Cert SSL        "  
baris_panjang
CLEAR
baris_panjang
echo -e "  9.) Clear Cache      "
echo -e " 10.) Clear Logs       "
baris_panjang
INFORMATION
baris_panjang
echo -e " 11.) Info Service Port  "
echo -e " 12.) Setting Limit IP & Quota "
baris_panjang
echo -e ""

}

function Select_Menu() {
read -p "Select From Options [1-22 or x] :  " NB
case $NB in
1) clear ; run ;;
2) clear ; reset ;;
3) clear ; semvak-autoreboot ;;
4) clear ; wget -q https://raw.githubusercontent.com/raffasyaa/skt/main/Tytyd/nameserver && chmod +x nameserver && ./nameserver && reset ;;
5) clear ; nano /etc/banner.txt ;;
6) clear ; change-domain ;;
7) clear ; fixhap ;;
8) clear ; fixcert ;;
9) clear ; clearcache ;;
10) clear ; clearlog ;;
11) clear ; Info_Port ;;
12) clear ; limit-on-off ;;
*) skarti-feature ;;
esac
}

Banner
Menu_Lambofgod
Select_Menu