#!/bin/bash
clear

# Mendefinisikan warna untuk pesan
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
export LIGHT='\033[0;37m'
export PINK='\033[0;35m'
export ORANGE='\033[38;5;208m'
export PINK_BG='\033[45;1;97m'
export BIRU='\033[44;1;97m'
export RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
export NC='\033[0m'
export INDIGO='\033[38;5;54m'
export TEAL='\033[38;5;30m'
export WHITE='\033[1;37m'

    echo -e "${CYAN} ——————————————————————————— ${NC} "
    echo -e " ${BIRU}         BOT NOTIF MENU    ${NC} "
    echo -e "${CYAN} ——————————————————————————— ${NC} "
    echo -e "  ${TEAL}[1]${NC}${WHITE} Add Bot Notifikasi${NC}"
    echo -e "  ${TEAL}[2]${NC}${WHITE} Delete Bot Notifikasi${NC}"
    echo -e "  ${TEAL}[x]${NC}${WHITE} Back To Menu${NC}"
    echo -e "${CYAN} ——————————————————————————— ${NC} "
    echo -e ""
read -p " ➣ Your Choice: " menu
case $menu in
1) clear ; skt-bot-notif-on ;;
2) clear ; skt-bot-notif-off ;;
x) clear ; menu ;;
esac
