#!/bin/bash
clear
# Mendefinisikan warna untuk pesan
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
export LIGHT='\033[0;37m'
export PINK='\033[0;35m'
export ORANGE='\033[38;5;208m'
export PINK_BG='\033[45;1;97m'
export BIRU='\033[44;1;97m'
export RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
export NC='\033[0m'
export INDIGO='\033[38;5;54m'
export TEAL='\033[38;5;30m'
export WHITE='\033[1;37m'
clear
# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Pastikan curl diinstal
if ! command -v curl &>/dev/null; then
  echo "curl tidak ditemukan, silakan instal terlebih dahulu!"
  exit 1
fi

# Mendapatkan informasi IP
echo "Mengambil informasi IP..."
ip_info=$(curl -s https://ipinfo.io)

# Mengekstrak data spesifik
ip=$(echo "$ip_info" | grep '"ip":' | sed -E 's/.*"ip": "(.*)",/\1/')
city=$(echo "$ip_info" | grep '"city":' | sed -E 's/.*"city": "(.*)",/\1/')
region=$(echo "$ip_info" | grep '"region":' | sed -E 's/.*"region": "(.*)",/\1/')
country=$(echo "$ip_info" | grep '"country":' | sed -E 's/.*"country": "(.*)",/\1/')
org=$(echo "$ip_info" | grep '"org":' | sed -E 's/.*"org": "(.*)",/\1/')

export TIME="10"
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear

# . Liner 
function baris_panjang() {
echo -e " ${TEAL}————————————————————————————————————————${NC}"
}

function xdxl_Banner() {
clear
baris_panjang
echo -e "  ${PURPLE}        SKARTI TUNNELING ${NC}"
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "\033[2;35m      Terimakasih sudah menggunakan \033[0m"
echo -e "\033[2;35m         Script Credit by skarti \033[0m"
baris_panjang
exit 1
}

# // jalankan perintah sleep 3 & loading $!
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}

xdxl_Banner
  echo -e ""
  echo -e " ${WHITE}Just input a number for${NC} ${GREEN}Limit IP${NC}"
  echo -e ""
  echo -e " ${YELLOW}0${NC} for No Limit"
  echo -e ""
baris_panjang
echo ""
read -p " Username      : " Login
read -p " Password      : " Pass
read -p " Limit (IP)    : " iplimit
read -p " Expired (day) : " masaaktif
echo
clear

#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip/
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"| passwd $Login &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="1024"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "1024" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
  echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
else
echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
fi
clear

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>————————————————————————————————————</code>
<code>    Account Created Successfully    </code>
<code>————————————————————————————————————</code>
<code>Host          : </code> <code>$domain</code>
<code>Username      : </code> <code>$Login</code>
<code>Password      : </code> <code>$Pass</code>
<code>Limit Device  : </code> <code>$iplimit</code>
<code>————————————————————————————————————</code>
<code>OpenSSH       : 443, 80, 22</code>
<code>Dropbear      : 443, 109</code>
<code>UDPGW         : 7100 - 7300</code>
<code>SSH UDP       : 1-65535 </code>
<code>SSH CDN WS    : 80, 8080, 8081-9999 </code>
<code>SSH CDN WSS   : 443</code>
<code>SSL/TLS       : 400-900</code>
<code>OpenVPN WS    : 443</code>
<code>OpenVPN SSL   : 443</code>
<code>OpenVPN TCP   : 80,1194</code>
<code>OpenVPN UDP   : 2200</code>
<code>————————————————————————————————————</code>
<code>GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Ping: clients3.google.com[crlf]Sec-WebSocket-Extensions: superspeed[crlf][crlf]</code>
<code>————————————————————————————————————</code>
<code>OVPN Download :</code> https://$domain:81/
<code>————————————————————————————————————</code>
<code>Expired On    : $expe</code>
<code>————————————————————————————————————</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>—————————————————————————————————</code>
<code>     💎 YOUR ACCOUNT VIP 💎</code>
<code>—————————————————————————————————</code>
<code>~ Aplikasi    : Skarti VPN Pro</code>
<code>~ Username    :</code><code> $Login</code>
<code>~ Password    :</code><code> $Pass</code>
<code>—————————————————————————————————</code>
<code>      🕊️ RULES SERVER 🕊️</code>
<code>—————————————————————————————————</code>
<code>~ Info Region : $country, $region</code>
<code>~ Kadaluarsa  : $expe</code>
<code>~ Max Login   : $iplimit Device</code>
<code>~ Multi Login : Auto Lock</code>
<code>~ Membeli     : Menyetujui</code>
<code>~ Membeli     : Memahami</code>
<code>~ No Reffund  : No Debat</code>
<code>—————————————————————————————————</code>
<code>       Jangan Di Share </code>
<code>    Maksimal Login 2 Device </code>
<code>—————————————————————————————————</code>
<code>         Terima Kasih </code>
<code>     Atas Kepercayaan Anda</code>
<code>—————————————————————————————————</code>"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Ping: clients3.google.com[crlf]Sec-WebSocket-Extensions: superspeed[crlf][crlf]"

PAYLOADTLS="GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADHANCED="HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf]"

# Details ACcount
function Details_Ssh(){
xdxl_Banner
echo -e " ${PURPLE}           SSH/Dropbear${NC}"
baris_panjang
echo -e "\033[3;37m Host         : $domain \033[0m"
echo -e "\033[3;37m Username     : $Login \033[0m"
echo -e "\033[3;37m Password     : $Pass \033[0m"
echo -e "\033[3;37m Limit IP     : ${iplimit} Device \033[0m"
baris_panjang
echo -e "\033[3;37m OpenSSH      : 22, 80 \033[0m"
echo -e "\033[3;37m Dropbear     : 80, 143 \033[0m"
echo -e "\033[3;37m OpenSSH SSL  : 443 \033[0m"
echo -e "\033[3;37m Dropbear SSL : 443 \033[0m"
baris_panjang
echo -e "\033[3;37m SSH WS NTLS  : 80,8080,8880,2082 \033[0m"
echo -e "\033[3;37m SSH WS TLS   : 443 \033[0m"
baris_panjang
echo -e "\033[3;37m SSH UDP      : 1-65535 \033[0m"
echo -e "\033[3;37m OpenVPN UDP  : 2200 \033[0m"
baris_panjang
}



function Copy_Faste(){
echo -e " ${PURPLE}             OpenVPN${NC}"
baris_panjang
echo -e "\033[3;37m https://$domain:81/ "
}



function Details_Payload(){
baris_panjang
echo -e " ${PURPLE}            Payload WS${NC}"
baris_panjang
echo -e "\033[3;37m ${PAYLOADWS}\033[0m"
baris_panjang
}



function Expiry_Details(){
echo -e "\033[33m       Expired  : $expe \033[0m"
}


xdxl_Banner
Details_Ssh
Copy_Faste
Details_Payload
Expiry_Details
Sc_Credit
